name: ğŸ•Šï¸ Bevy CI
description: Runs clippy and test suite

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: ğŸŒˆ Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 

      - name: ğŸŒˆ Check format
        shell: bash
        run: cargo fmt --check
  clippy:
    name: ğŸ“ Clippy
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 

      - name: ğŸ“¦ Install Bevy Dependencies
        uses: bevyengine/bevy/.github/actions/install-linux-deps@9a0bfc6f14241d58e6d4d1bc7ce72ebaa673b695

      - name: ğŸ“ Clippy
        shell: bash
        run: cargo clippy
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 

      - name: ğŸ“¦ Install Bevy Dependencies
        uses: bevyengine/bevy/.github/actions/install-linux-deps@9a0bfc6f14241d58e6d4d1bc7ce72ebaa673b695

      - name: ğŸ§ª Run tests
        run: cargo test
